name: Build QML Remote Server

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-appimage:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          wget \
          file \
          libfuse2 \
          python3-pip \
          imagemagick \
          libgl1-mesa-dev \
          libxkbcommon-dev \
          libxrandr2 \
          libxss1 \
          libgconf-2-4 \
          libasound2-dev
          
    - name: Build AppImage
      run: |
        ./ci/deploy/linux/build-appimage.sh
        
    - name: Test AppImage
      run: |
        ls -la *.AppImage
        file *.AppImage
        echo "AppImage created successfully"
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: QML-Remote-Server-Linux-x86_64
        path: "*.AppImage"
        retention-days: 30
