name: Build QML Remote Server

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Qt6 and dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          qt6-base-dev \
          qt6-declarative-dev \
          qml6-module-qtquick \
          qml6-module-qtquick-controls \
          qml6-module-qtquick-layouts \
          qml6-module-qtquick-window \
          cmake \
          ninja-build \
          build-essential \
          libgl1-mesa-dev \
          libxkbcommon-dev
          
    - name: Create build directory
      run: mkdir -p builds/Qt-6.5.3-linux-g++/Debug
      
    - name: Configure CMake
      run: |
        cd builds/Qt-6.5.3-linux-g++/Debug
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6 \
          ../../..
          
    - name: Build
      run: |
        cd builds/Qt-6.5.3-linux-g++/Debug
        ninja
        
    - name: Test executable exists
      run: |
        test -f builds/Qt-6.5.3-linux-g++/Debug/appqml-remoteserver
        echo "Build successful - executable created"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qml-remoteserver-ubuntu22.04
        path: |
          builds/Qt-6.5.3-linux-g++/Debug/appqml-remoteserver
          examples/
        retention-days: 30
